- android/src/com/google/zxing/client/android/camera/CameraManager.java
- android/src/com/google/zxing/client/android/camera/open/OpenCameraInterface.java
This patch simply updates CameraManager and OpenCameraInterface by removing unneeded code.
> Removing unnecessary code from CameraManager

- core/src/main/java/com/google/zxing/pdf417/encoder/PDF417HighLevelEncoder.java
This is to fix the bug reported in https://groups.google.com/forum/#!topic/zxing/q7GQpSAbWk8
> Fix PDF417 numeric encoding grouping index check

- android/res/values-it/strings.xml
- android/res/values/strings.xml
- android/res/xml/preferences.xml
- android/src/com/google/zxing/client/android/CaptureActivity.java
- android/src/com/google/zxing/client/android/PreferencesActivity.java
- android/src/com/google/zxing/client/android/history/HistoryManager.java
Added a new preference to enable and disable history saving (enabled by default).
> Added the ability to disable history saving

- core/src/main/java/com/google/zxing/datamatrix/DataMatrixWriter.java
> Revert "minSize from provided sizes"

- core/src/main/java/com/google/zxing/pdf417/encoder/PDF417HighLevelEncoder.java
- core/src/test/java/com/google/zxing/pdf417/encoder/PDF417EncoderTestCase.java
Unittest and possible fix for https://github.com/zxing/zxing/issues/394
> Multibyte fix

- android/res/values-sl/strings.xml
> Improved Slovenian translation

- core/src/main/java/com/google/zxing/pdf417/PDF417Writer.java
- fine-grained scaling for PDF_417 generation
#418
> Set PDF_417 lineThickness to 1

- core/src/main/java/com/google/zxing/MultiFormatWriter.java
- core/src/main/java/com/google/zxing/oned/UPCEANReader.java
- core/src/main/java/com/google/zxing/oned/UPCEReader.java
- core/src/main/java/com/google/zxing/oned/UPCEWriter.java
> Add support encoding UPC-E format

- README.md
It is really hard to find the instruction.
> Added the "Get Started Developing" link in the README.md

- android/res/values-pl/strings.xml
I attempted to correct some Polish translations.  I'm fairly sure my first commit actually fixes two errors, but I don't recommend accepting the second one without a native speaker's approval (and probably some corrections to my corrections).
I hereby grant everyone the right to use and distribute this contribution under the same terms as the original program.
> Polish corrections

- core/src/main/java/com/google/zxing/pdf417/decoder/DecodedBitStreamParser.java
- core/src/main/java/com/google/zxing/qrcode/decoder/BitMatrixParser.java
- core/src/main/java/com/google/zxing/qrcode/decoder/DataMask.java
- core/src/main/java/com/google/zxing/qrcode/decoder/DecodedBitStreamParser.java
- core/src/main/java/com/google/zxing/qrcode/decoder/FormatInformation.java
- core/src/main/java/com/google/zxing/qrcode/encoder/MaskUtil.java
- core/src/main/java/com/google/zxing/qrcode/encoder/MatrixUtil.java
- core/src/test/java/com/google/zxing/qrcode/decoder/DataMaskTestCase.java
- core/src/test/java/com/google/zxing/qrcode/encoder/MaskUtilTestCase.java
I simplified a couple of pieces of code while keeping the behavior the same. The message in each commit explains what happened.
> Simplified pieces of code

- core/src/main/java/com/google/zxing/qrcode/decoder/DataMask.java
Further micro-optimize QR data mask recognition; more comment for earlier such changes.
> Further micro-optimize QR data mask recognition; more comment for earlier such changes.

- core/src/main/java/com/google/zxing/Result.java
- core/src/main/java/com/google/zxing/aztec/AztecReader.java
- core/src/main/java/com/google/zxing/aztec/decoder/Decoder.java
- core/src/main/java/com/google/zxing/common/DecoderResult.java
- core/src/main/java/com/google/zxing/multi/GenericMultipleBarcodeReader.java
- core/src/test/java/com/google/zxing/aztec/decoder/DecoderTest.java
See https://github.com/zxing/zxing/issues/644
CC @fgrieu
> Add 'getNumBits' to Result objects to return when not all bits of the raw byte representation are valid

- README.md
Thanks for the great job and inspiration.
Sincerely,
> Change README.md. Added Delphi/Pascal ZXing reference.

- android/res/values-ca/strings.xml
> Fix a typo in Catalan

- core/src/test/java/com/google/zxing/RGBLuminanceSourceTestCase.java
Couple of extra tests to get better code coverage in `RGBLuminanceSource`.
> Add new matrix tests in RGBLuminanceSourceTestCase

- core/src/main/java/com/google/zxing/common/HybridBinarizer.java
Moved a couple of calculations out of for loops if they aren't affected by the for loop to avoid recalculating the same value.
> Minor performance improvements to HybridBinarizer

- core/src/main/java/com/google/zxing/oned/Code128Writer.java
- core/src/test/java/com/google/zxing/oned/Code128WriterTestCase.java
if I'm not wrong this PR addresses the issue #649
> Add codeset A support to Code 128

- javase/src/main/java/com/google/zxing/client/j2se/DecodeWorker.java
Hey, I have fixed NullPointerException however I am not able to write the test as the code that was failing consist our customers data :( 
However, after this fix the library finally reads code correctly.
> Fix null pointer exception in DecodeWorker.java

- core/src/main/java/com/google/zxing/qrcode/detector/FinderPatternFinder.java
- core/src/test/java/com/google/zxing/qrcode/QRCodeBlackBox2TestCase.java
- core/src/test/java/com/google/zxing/qrcode/QRCodeBlackBox3TestCase.java
- core/src/test/java/com/google/zxing/qrcode/QRCodeBlackBox5TestCase.java
Adding diagonal check to solve #897 to prevent false positives for centers.
> Add QRCode lenient diagonal check

- core/bnd.bnd
- core/pom.xml
Add the necessary config to generate OSGi-Metainfos
> Fix #957 - Provide OSGi Metadata in Manifest

- android/assets/html-es/about1d.html
- android/assets/html-es/about2d.html
- android/assets/html-es/license.html
- android/assets/html-es/scanning.html
- android/res/values-es/strings.xml
Here are some corrections in Spanish assests.
> Corrections

- core/src/main/java/com/google/zxing/EncodeHintType.java
- core/src/main/java/com/google/zxing/qrcode/encoder/Encoder.java
Manual selection of the mask pattern greatly improves performance.
> Minor change to enable manual selection of the QR code mask pattern

- core/src/main/java/com/google/zxing/ResultMetadataType.java
> Fix typo in ResultMetadataType.java

- core/src/main/java/com/google/zxing/EncodeHintType.java
- core/src/main/java/com/google/zxing/common/ECIEncoderSet.java
- core/src/main/java/com/google/zxing/datamatrix/DataMatrixWriter.java
- core/src/main/java/com/google/zxing/datamatrix/encoder/HighLevelEncoder.java
- core/src/main/java/com/google/zxing/datamatrix/encoder/MinimalEncoder.java
- core/src/main/java/com/google/zxing/qrcode/encoder/MinimalEncoder.java
- core/src/test/java/com/google/zxing/datamatrix/encoder/HighLevelEncodeTestCase.java
Feature is off by default and can be activated by EncodeTypeHint.DATA_MATRIX_COMPACT
> Minimal encoding for Data Matrix with multi ECI and GS1-FNC1 support (2nd)

- core/src/main/java/com/google/zxing/EncodeHintType.java
- core/src/main/java/com/google/zxing/oned/Code128Writer.java
- core/src/test/java/com/google/zxing/oned/Code128WriterTestCase.java
Added CODE128_COMPACT encoding hint for activation.
> Minimal encoding for Code-128 (2nd, less intrusive version)

- README.md
* Added SCodes link to 3rd party projects section
> Update README.md: Add SCodes Qt/Qml wrapper library link

- core/src/main/java/com/google/zxing/pdf417/encoder/PDF417HighLevelEncoder.java
- core/src/test/java/com/google/zxing/pdf417/encoder/PDF417EncoderTestCase.java
> Prevent encoding of the empty string for PDF417

- core/src/main/java/com/google/zxing/oned/Code128Writer.java
Removing the forced content limit check as per https://github.com/zxing/zxing/issues/1672
> Removing the forced content limit check for Code128Writer.java

- README.md
Add info about the new wrappers of zxing-cpp.
> README.md: zxing-cpp update

- core/src/main/java/com/google/zxing/client/result/EmailDoCoMoResultParser.java
- core/src/test/java/com/google/zxing/client/result/EmailAddressParsedResultTestCase.java
- core/src/test/java/com/google/zxing/client/result/ParsedReaderResultTestCase.java
> Be more stringent on email validation rules

- core/src/main/java/com/google/zxing/qrcode/detector/FinderPatternFinder.java
- core/src/test/java/com/google/zxing/qrcode/QRCodeBlackBox3TestCase.java
Fix distortion calculation for isosceles right triangles as discussed in https://github.com/zxing/zxing/discussions/1906
> Fix distortion calculation for isosceles right triangles
