zxing/zxing

android/src/com/google/zxing/client/android/CaptureActivity.java

When using the QR code reader with a front facing camera (non-default camera) if you turn the screen off and on (pressing power button) the camera being used changes to the default camera. This occurs because when the screen is turned off and on the surfaceView is not destroyed causing a different  behavior in CaptureActivity.onResume(). The surfaceView not being destroyed causes the CameraManager to open the camera before setting the cameraId. This pull request has reordered these operations to make sure the manual setting of cameraId inside CaptureActivity.onResume() occurs before the CameraManager opening the camera.
For more information see the following post:
https://groups.google.com/forum/#!topic/zxing/CguxsAm0SjE

Fixed the cameraId changing on powerbutton press

---

android/src/com/google/zxing/client/android/result/supplement/TitleRetriever.java

This allows page titles with HTML entities like `&amp;` to display properly. Before, no decoding would be performed and `&amp;` would be shown where an ampersand should be. Additionally, decoding entities prevents the following string length check from overcounting.
To replicate this bug scan an image with a URL pointing to http://stackoverflow.com/questions/tagged/android The title displayed within the app will be something like: `Frequent &#39;android&#39; Questions - Stack Overflow` After this commit, the app will display the correct decoded title: `Frequent 'android' Questions - Stack Overflow`
Alternatively, scan this to replicate:

Decode HTML entities in titles

---

core/src/main/java/com/google/zxing/pdf417/encoder/PDF417HighLevelEncoder.java
core/src/test/java/com/google/zxing/pdf417/encoder/PDF417EncoderTestCase.java

Fixed a bug when calling String.substring introduced in https://github.com/zxing/zxing/pull/395, which caused an exception when for example trying to encode "sadfg$sad" in PDF417 with the default encoding (ISO-8859-1)

Fixed substring call

---

core/src/main/java/com/google/zxing/EncodeHintType.java
core/src/main/java/com/google/zxing/pdf417/PDF417Writer.java

I ran across this limitation while comparing zxing PDF417 output to Okapi PDF417 output.
The contribution is my original work and I license the work to the project under the project's open source license.

PDF417Writer shouldn't ignore ERROR_CORRECTION hint

---

core/src/test/java/com/google/zxing/BufferedImageLuminanceSource.java
javase/src/main/java/com/google/zxing/client/j2se/BufferedImageLuminanceSource.java

RGB to gray, the weight of R is 0.299, not 0.229.  The comment have a little error. And why add 0x200 ? It may be a error.  306/1024 = 0.2988.  601/1024=0.5869 and 117/1027 = 0.1143.

fix a little error

---

core/src/main/java/com/google/zxing/qrcode/encoder/Encoder.java
core/src/test/java/com/google/zxing/qrcode/encoder/EncoderTestCase.java

I've used a QRCode Encoder.
When Charset is Shift_JIS, byte mode has been chosen in the content of numeric data.
```
Map<EncodeHintType,Object> hints = new EnumMap<>(EncodeHintType.class);
hints.put(EncodeHintType.CHARACTER_SET, "Shift_JIS");
QRCode qrCode = Encoder.encode("0123", ErrorCorrectionLevel.M, hints);
System.out.println(qrCode.getMode()); // -> BYTE
```
I think should be chosen numeric mode.

QRCode Encoder: Support NUMERIC/ALPHANUMERIC Mode in Shift_JIS

---

javase/src/main/java/com/google/zxing/client/j2se/DecodeWorker.java

@srowen This pull request resolves a race condition seen in printing output in the command line runner. I'm not entirely sure why this occurs, but presumably the multithreaded execution of the command line runner can cause the `println` calls to be executed out of order. This is apparently something that [can happen with println in multithreaded execution](http://stackoverflow.com/questions/19460987/why-is-system-out-prinln-out-of-order).
I found this occurs in two cases in my OS X environment. The first was when one of the input files is a symlink to another of input files. The second was when the files had very recently been written to disk by another program. I'm guessing in both cases, the data is already in memory, making the race condition more likely. The goofy output looks like …

Use StringWriter to prevent race condition in println

---

core/src/main/java/com/google/zxing/pdf417/encoder/PDF417.java

Found a couple of spelling mistakes in a hard coded error message. This PR fixes this mistake.

Fix spelling mistake in error message

---

core/src/main/java/com/google/zxing/aztec/decoder/Decoder.java
core/src/test/java/com/google/zxing/aztec/decoder/DecoderTest.java

The Aztec decoder now packs the code bits into bytes and returns them as "raw bytes", even though the error correction codes and stuffing have been already removed.  Also added a couple of test cases for the byte-packing function.  This fixes issue #381.
I hereby grant everyone the right to use and distribute this contribution under the same terms as the original program.

Aztec decoder returns raw bytes

---

core/src/main/java/com/google/zxing/EncodeHintType.java
core/src/main/java/com/google/zxing/qrcode/encoder/Encoder.java
core/src/test/java/com/google/zxing/qrcode/encoder/EncoderTestCase.java

Add a hint to allow the ability to specify a specific version of QR code. If the specified content won't fit in the version, an exception is thrown. If no hint is provided, the current method of selecting the "smallest" version that fits is used.
(I wanted to be able to generate a replica of a code that I had the content for.)

Add ability to specify a QR code version hint.

---

android/src/com/google/zxing/client/android/wifi/NetworkType.java

Make zxing recognize WIFI qrcodes with the type field set to WPA2 as WPA.

I've seen some codes with the type set to WPA2

---

README.md

I would like to request the update of QZXing's project repository URL in order to keep the readme file up-to-date. 
Previous location: [SourceForge](https://sourceforge.net/projects/qzxing/)
New location: [GitHub](https://github.com/ftylitak/qzxing)

Updated QZXing's URL (port to Qt framework)

---

core/src/main/java/com/google/zxing/common/reedsolomon/ReedSolomonEncoder.java
zxing.appspot.com/src/main/java/com/google/zxing/web/generator/client/ContactInfoGenerator.java

I found two typos in the Javadocs and fixed them

Fix two typos in Javadocs

---

core/src/main/java/com/google/zxing/oned/ITFWriter.java

The intermediate array only needs to be 10 ints long, not 18. The max value for `j` is 4, so `2 * 4 + 1 = 9`.

Correct size of array in ITFWriter

---

README.md

The ZXing.NET project is originally hosted on CodePlex, but Microsoft shut down the site recently, then the developer moved it to GitHub. So I update the link.

Update ZXing.NET project link

---

core/src/main/java/com/google/zxing/oned/UPCEWriter.java

Looks like some debugging code got left in the UPCEWriter class. Presumably there's no reason to keep it in the codebase.

Drop debugging code from UPCEWriter

---

android/src/com/google/zxing/client/android/result/WifiResultHandler.java

AndroidStudio reported the error:
Error: The WIFI_SERVICE must be looked up on the Application context or memory will leak on devices < Android N. Try changing to .getApplicationContext()  [WifiManagerLeak]

Fixed Wifi mangager memory leak on devices < N

---

README.md

Added a https://github.com/dsiddharth2/php-zxing link to ZXing-based third-party open source projects area.

Updated php-zxing link

---

zxingorg/src/main/java/com/google/zxing/web/DecodeServlet.java

doPost() works only with badimage

Fixed error key in doPost()

---

android/src/com/google/zxing/client/android/wifi/NetworkType.java
android/src/com/google/zxing/client/android/wifi/WifiConfigManager.java
core/src/main/java/com/google/zxing/client/result/WifiParsedResult.java
core/src/main/java/com/google/zxing/client/result/WifiResultParser.java

This adds support for parsing QR codes which contain information about an WPA2 enterprise (EAP) network.
For WPA2 enterprise, strings will be of the form:
WIFI:T:WPA2-EAP;S:[network SSID];H:[hidden?];E:[EAP method];PH2:[Phase 2 method];AI:[anonymous identity];I:[username];P:[password];;
The "EAP method" can e.g. be "TTLS" or "PWD" or one of the other fields in [WifiEnterpriseConfig.Eap ](https://developer.android.com/reference/android/net/wifi/WifiEnterpriseConfig.Eap.html) and "Phase 2 method" can e.g. be "MSCHAPV2" or any of the other fields in [WifiEnterpriseConfig.Phase2](https://developer.android.com/reference/android/net/wifi/WifiEnterpriseConfig.Phase2.html)
An example would be:
WIFI:S:eduroam;T:WPA2-EAP;AI:anonymous@uni-stuttgart.de;I:username@uni-stuttgart.de;P:password;E:PEAP;PH2 …

Implement support for WPA2 Enterprise (EAP)

---

core/src/main/java/com/google/zxing/EncodeHintType.java
core/src/main/java/com/google/zxing/qrcode/encoder/Encoder.java
core/src/test/java/com/google/zxing/qrcode/encoder/EncoderTestCase.java

This PR adds support for encoding GS1 formatted QR's through the addition of an encoding hint. Basically for the QR to meet the GS1 standard we must prefix the header bit stream with the FNC1 mode header. Prior to this PR there was no means of adding this header.

Add support for encoding GS1 formatted QR

---

README.md

zxing-ts is a port of this lib, written in TS and compiled as a node_module, compatible with any TS projects, including Angular 5.

Aadded zxing-ts to 3-party projects

---

core/src/main/java/com/google/zxing/datamatrix/DataMatrixWriter.java

Hi @srowen , was wondering if you'd like to go over my proposed fix for this issue. Tried it locally and it works, passes unit tests, etc. Let me know if further changes are needed and i will follow through accordingly. 
Thanks!

Proposed fix for Issue #836 - height and width parameters ignored when barcode_format is DATA_MATRIX

---

android/src/com/google/zxing/client/android/camera/CameraConfigurationManager.java
android/src/com/google/zxing/client/android/camera/CameraManager.java

Hi there,
Thanks for your great work!
I have tested ZXing on my Nexus 4 and found it suffers from a low frame rate issue. The camera is very slow and appears choppy on Nexus 4. Although it does not affect the major functionality but it still affects the usability.
I also found the following Stack Overflow discussions and adopted the workaround in this pull request.
Reference Stack Overflow Posts:
[Stack Overflow Post 1](https://stackoverflow.com/questions/20252352/image-preview-is-very-slow-on-nexus4)
[Stack Overflow Post 2](https://stackoverflow.com/questions/14131900/extreme-camera-lag-on-nexus-4)
Thanks! If you need further information, I may make a video to show the slow camera on Nexus 4.

Added a workaround for low framerate issue on Nexus 4

---

android/src/com/google/zxing/client/android/result/ResultHandler.java

IMPP field can be set [to a URI][0]. If that URI is of XMPP scheme set the protocol used to JABBER and drop the scheme part from the IM handle.
This format is used by XMPP messengers e.g. [Conversations.im][1].
[0]: https://tools.ietf.org/html/rfc6350#section-6.4.3
[1]: https://github.com/siacs/Conversations/blob/master/README.md#how-does-the-address-book-integration-work

Set protocol to JABBER if XMPP IM handle is found

---

README.md

I was the previous owner of a port/fork of Zxing library, now I moved it into an org.

Fixed my port name and URL (zxing-ts)

---

core/src/main/java/com/google/zxing/common/BitArray.java
core/src/main/java/com/google/zxing/common/BitMatrix.java

Optimize buffer size in `BitMatrix.xor()` and `BitArray.toString()`.
In BitMatrix.xor(), small buffer size causes allocation of BitArray every time in following loop.
(see BitMatrix.getRow)
BitArray change is just optimization.

Optimize buffer size

---

core/src/main/java/com/google/zxing/common/reedsolomon/GenericGFPoly.java
core/src/test/java/com/google/zxing/common/reedsolomon/ReedSolomonTestCase.java

GenericGFPoly.toString() returns empty string (`""`) when that is zero.
It should be `"0"`.

String of zero polynomial be "0"

---

core/src/main/java/com/google/zxing/common/reedsolomon/GenericGFPoly.java
core/src/test/java/com/google/zxing/common/reedsolomon/GenericGFPolyTestCase.java

Does your modification intend to remove spaces around minus sign on head of polynomial?
I found a bug that string of `GenericGFPoly(QR_CODE_FIELD_256, new int[] {3})` should be `"a^25"`, not `"3"`.

Remove spacing from head of polynomial string

---

core/src/main/java/com/google/zxing/qrcode/decoder/DecodedBitStreamParser.java
core/src/test/java/com/google/zxing/qrcode/decoder/DecodedBitStreamParserTestCase.java

Some hanzi characters (`A560` to `AAFE` on BG2312) could not be decoded, by wrong border value.
The new value `0xA00` means `0xB0A1 - 0xA6A1`.

Fix QR-code hanzi segment decoder

---

core/src/main/java/com/google/zxing/oned/EAN13Writer.java
core/src/main/java/com/google/zxing/oned/EAN8Writer.java
core/src/main/java/com/google/zxing/oned/ITFWriter.java
core/src/main/java/com/google/zxing/oned/OneDimensionalCodeWriter.java
core/src/main/java/com/google/zxing/oned/UPCEWriter.java
core/src/test/java/com/google/zxing/oned/EAN13WriterTestCase.java
core/src/test/java/com/google/zxing/oned/EAN8WriterTestCase.java
core/src/test/java/com/google/zxing/oned/ITFWriterTestCase.java
core/src/test/java/com/google/zxing/oned/UPCEWriterTestCase.java

Several barcode formats only support digits 0-9, namely
- BarcodeFormat.EAN_13 
- BarcodeFormat.EAN_8 
- BarcodeFormat.ITF 
- BarcodeFormat.UPC_EAN_EXTENSION
Passing different characters to the encode function causes a runtime exception. 
**Proposed solution**
Check return value of Character.digit and throw IllegalArgumentException if it is -1 (invalid character.)
Source: https://developer.android.com/reference/java/lang/Character#digit(int,%20int)

Check if characters are digits for EAN_13, EAN_8, ITF and UPC_EAN_EXTENSION

---

core/src/main/java/com/google/zxing/aztec/encoder/State.java
core/src/test/java/com/google/zxing/aztec/encoder/EncoderTest.java

This introduces some tests that show that the current heuristic that determines whether an encoding state can savely been dropped isn't valid for binary shift mode. That flaw may lead to inefficent encoding for non-textual data, i.e. the encoding uses some more bytes than the original octet encoding does.
It also comes with the fix for that heuristic.

fix binary shift cost heuristics

---

android/src/com/google/zxing/client/android/history/HistoryManager.java

The correct pattern to make a directory is: `if (!dir.mkdirs() && !dir.isDirectory()) { error }` mkdirs checks for exists so the exists check is redundant.

Directory Bug

---

core/src/test/java/com/google/zxing/common/BitArrayTestCase.java

I am currently porting commits to the ZXingObjC project. As I read through the code, I believe I found a small mistake.
I guess you want to test for `a != b` after setting a bit.

Fixed duplicated assertion

---

core/src/main/java/com/google/zxing/oned/UPCEWriter.java

I am still porting commits to the ZXingObjC project. As I read through the code, I believe I found a small mistake: according to EAN13Writer, both possibilities (7 or 8 digits) should be reflected within the message.

Corrected exception message in UPCEWriter

---

core/src/main/java/com/google/zxing/oned/EAN8Writer.java

I am still porting commits to the ZXingObjC project. As I read through the code, I believe I found a small mistake: according to EAN13Writer, both possibilities (7 or 8 digits) should be reflected within the message.

Corrected exception message in EAN8Writer

---

core/src/main/java/com/google/zxing/oned/Code93Reader.java
core/src/test/java/com/google/zxing/oned/Code93ReaderTestCase.java

Some characters (`(%)U`, `(%)V` and `(%)W` map to `NUL`, `'@'` and ``'`'``) were decoded to wrong value `DEL` in Code93Reader.

fix code93 extended character decoder

---

core/src/main/java/com/google/zxing/oned/Code39Writer.java

Every code39 character has 9 bars containing 3 wide bars, and separated by a white bar.
`(9-3)*1 + 3*2 + 1 = 13`

Optimize code width calculation in Code39Writer

---

core/src/main/java/com/google/zxing/oned/Code128Writer.java
core/src/test/java/com/google/zxing/oned/Code128WriterTestCase.java

The string `"\n\u00f4\n" (LF FNC4 LF)` should be encoded to:
`START_CODE_A + LF + FNC4A + LF + checksum + STOP`
but got:
`START_CODE_A + LF + SWITCH_CODE_B + FNC4B + SWITCH_CODE_A + LF + checksum + STOP`.
It should be able to continue in codeset A when character encoded FNC4.
Also single number and FNC1-3 are continuable.

Continue in codeset A when character encoded single number or FNC1-4 in Code128Writer

---

android/src/com/google/zxing/client/android/book/SearchBookContentsActivity.java

Reproducible with
`Intent i = new Intent("com.google.zxing.client.android.SEARCH_BOOK_CONTENTS");
startActivity(i);`

Avoid book search crash on invalid intent

---

core/src/main/java/com/google/zxing/multi/qrcode/QRCodeMultiReader.java
core/src/test/java/com/google/zxing/multi/qrcode/MultiQRCodeTestCase.java

When I read QR codes which has a structured append header, The result list contains duplicated data.
ex:
(ISO/ICE 18004 Figure 22)
`QRCodeMultiReader.decodeMultiple` returns 5 results (each qr-code data and a combined data).
It should be just combined one, I think.
I'm no sure it is a bug or not, but I want to fix it.

Remove duplicate results when it has structured append header.

---

core/pom.xml

Add `Automatic-Module-Name` entry of `com.google.zxing`
to the core JAR for Java Platform Module System.
See Issue #1154 
This contribution is my original work and I license the work to the project under the project's open source license.

core JAR Automatic-Module-Name: com.google.zxing

---

AUTHORS
core/src/main/java/com/google/zxing/qrcode/detector/FinderPatternFinder.java
core/src/test/java/com/google/zxing/qrcode/QRCodeBlackBox2TestCase.java

I rewrote the `FinderPatternFinder.selectBestPatterns()`.
I got a better score on blackbox test 2, and same scores on other blackbox tests.
In addition, this improvement makes some QR-codes readable which reported in #1157 and #1144.

Improve FinderPatternFinder.selectBestPatterns

---

core/src/main/java/com/google/zxing/oned/CodaBarWriter.java

I found that the format parameter is not checked in `CodaBarWriter.encode()`.
Other oned-writers have a code to check it.

Checking the format parameter in the CodaBarWriter.

---

core/src/main/java/com/google/zxing/oned/rss/RSS14Reader.java
core/src/test/java/com/google/zxing/oned/rss/RSS14BlackBox2TestCase.java

The second value of `findFinderPattern()` points the outside pixel of the finder pattern (see [RSS14Reader.java:L301-306](/zxing/zxing/blob/6075d5b2f69f285657ff65b0abcc7c7885a44eed/core/src/main/java/com/google/zxing/oned/rss/RSS14Reader.java#L301-L306)).
I’ｍ going to fix two points in this PR.
1. `ResultPointCallback` parameter will be real center point of the finder pattern.
2.  The _inside char_ will be started from the next pixel of the finder pattern.

Fix handling of the second value of findFinderPattern() 

---

android/res/xml/preferences.xml
android/src/com/google/zxing/client/android/camera/CameraConfigurationManager.java

* This is supported on almost all devices now, and they handle this pretty
well. Additionally, this workarounds a bug in some devices which auto mode
will hang forever for unknown reason.

Default to allow focusing in continuous-picture mode

---

.github/CONTRIBUTING.md

There was 2 titles in which markup was not working.

Fixing CONTRIBUTORS.md section titles

---

.reuse/dep5
pom.xml

Hi,
This pull request does the following:
* Specifies the license and copyrights prominently in the README file
* Updates the copyrights in the main POM file
* Adds [REUSE metadata](https://reuse.software/spec/) for the currently checked in source code
You may also want to review the information in LICENSE, NOTICES and README and decide whether the historical bits still need to be kept.

License and copyrights

---

README.md

add pyzxing in ZXing-based third-party open source projects table

add a Python wrapper to ZXing library

---

core/src/main/java/com/google/zxing/multi/qrcode/detector/MultiFinderPatternFinder.java

As comented before in #1312 , MultiFinderPatternFinder can be a public class like its parent.

Make MultiFinderPatternFinder a public class

---

core/src/main/java/com/google/zxing/aztec/AztecWriter.java
core/src/main/java/com/google/zxing/aztec/decoder/Decoder.java
core/src/main/java/com/google/zxing/aztec/encoder/Encoder.java
core/src/main/java/com/google/zxing/aztec/encoder/HighLevelEncoder.java
core/src/main/java/com/google/zxing/aztec/encoder/State.java
core/src/main/java/com/google/zxing/common/CharacterSetECI.java
core/src/main/java/com/google/zxing/common/StringUtils.java
core/src/main/java/com/google/zxing/datamatrix/decoder/DecodedBitStreamParser.java
core/src/main/java/com/google/zxing/pdf417/decoder/DecodedBitStreamParser.java
core/src/main/java/com/google/zxing/pdf417/encoder/PDF417HighLevelEncoder.java
core/src/main/java/com/google/zxing/qrcode/decoder/DecodedBitStreamParser.java
core/src/main/java/com/google/zxing/qrcode/encoder/Encoder.java
core/src/test/java/com/google/zxing/aztec/detector/DetectorTest.java
core/src/test/java/com/google/zxing/aztec/encoder/EncoderTest.java
core/src/test/java/com/google/zxing/common/StringUtilsTestCase.java
core/src/test/java/com/google/zxing/qrcode/encoder/EncoderTestCase.java

Follow-up to https://github.com/zxing/zxing/pull/1328, which added charset-aware _decoding_ to Aztec Code.
* Make `AztecWriter` and `aztec.Encoder` insert ECI according to character set hint
* Add encoder and round-trip test cases using ECI (and fix an erroneous test case that only passed previously because it wasn't really doing a charset-aware decode)
* Simplify test cases to avoid unnecessary `String`/`byte[]` and `Charset`/`String` (charset name) conversions.
* Further removal of unnecessary `Charset`/`String` (charset name) conversions…
1. First, throughout the Aztec implementation
2. In PDF417, QR, and DataMatrix implementations too

Aztec encode with ECI for non-default character sets

---

core/src/main/java/com/google/zxing/pdf417/decoder/DecodedBitStreamParser.java
core/src/test/java/com/google/zxing/pdf417/decoder/PDF417DecoderTestCase.java

Decodes the Macro PDF417 "fileId" codewords as 0-899 numbers, each 0-filled to width 3. See https://github.com/nu-book/zxing-cpp/pull/219.
As mentioned there not doing any base 900 maths based on the example in ISO/IEC 15438:2015 Annex H.6, where (100, 200, 300) is transmitted as "100200300". Also as discussed there in the code review the old decoding as text can lose info if numeric codewords convert to shifts/latches etc.
Checks that `fileId` is not empty (mandatory field, Annex H.2).
Allows a symbol to consist solely of a Macro (i.e. checks for non-existence of `fileId` on result empty check), as stated in Annex H.2 note.
Unit test additions.

PDF417 Macro: fileId numeric decode; allow Macro only symbol

---

core/src/main/java/com/google/zxing/aztec/detector/Detector.java

small fix: valid `y` range

---

javase/src/main/java/com/google/zxing/client/j2se/DecodeWorker.java
javase/src/main/java/com/google/zxing/client/j2se/DecoderConfig.java

A small patch to add a --raw option to the CommandLineRunner to get the raw bitstream from the decode of the barcode. This is useful, especially when debugging encoding issues in barcode encoders. The same data is available in the web decoder, but sometimes the command line is easier.

Add option to output raw bitstream from CommandLineRunner.

---

core/src/main/java/com/google/zxing/aztec/decoder/Decoder.java
core/src/test/java/com/google/zxing/aztec/decoder/DecoderTest.java

I discovered that when decoding an Aztec GS1 barcode, all <GS> characters are output at the beginning of the stream. This patch fixes that.

Fix decoding of FNC1 in AztecCode.

---

core/src/main/java/com/google/zxing/datamatrix/encoder/MinimalEncoder.java
core/src/test/java/com/google/zxing/datamatrix/encoder/HighLevelEncodeTestCase.java

Fix for:
Exception in thread "main" java.lang.IllegalArgumentException: The number of codewords does not match the selected symbol
at com.google.zxing.datamatrix.encoder.ErrorCorrection.encodeECC200(ErrorCorrection.java:103)
at com.google.zxing.datamatrix.DataMatrixWriter.encode(DataMatrixWriter.java:112)

Fix for IllegalArgumentException encoding data-matrix with EncodeHintType.DATA_MATRIX_COMPACT

---

core/src/main/java/com/google/zxing/EncodeHintType.java
core/src/main/java/com/google/zxing/datamatrix/DataMatrixWriter.java
core/src/main/java/com/google/zxing/datamatrix/encoder/C40Encoder.java
core/src/main/java/com/google/zxing/datamatrix/encoder/HighLevelEncoder.java

Forces C40 encoding in data-matrix via EncodeHintType.FORCE_C40 (apparently a French government requirement).
Note that not all input strings can be encoded in C40.

Added option to force C40 encoding in data matrix

---

core/src/main/java/com/google/zxing/pdf417/decoder/DecodedBitStreamParser.java

Text compaction mode is the default mode and does not need to be specified (See "5.4.2.1 Text Compaction sub modes"; quote: "The default compaction mode for PDF417 in effect at the start of each symbol shall always be Text compaction mode Alpha sub mode [uppercase alphabetic]")

Fix bug #1502 that PDF417 barcodes without initial latch to Text compaction mode fail to decode

---

core/src/main/java/com/google/zxing/EncodeHintType.java
core/src/main/java/com/google/zxing/common/ECIInput.java
core/src/main/java/com/google/zxing/common/MinimalECIInput.java
core/src/main/java/com/google/zxing/datamatrix/encoder/MinimalEncoder.java
core/src/main/java/com/google/zxing/pdf417/PDF417Writer.java
core/src/main/java/com/google/zxing/pdf417/decoder/DecodedBitStreamParser.java
core/src/main/java/com/google/zxing/pdf417/encoder/PDF417.java
core/src/main/java/com/google/zxing/pdf417/encoder/PDF417HighLevelEncoder.java
core/src/main/java/com/google/zxing/pdf417/encoder/PDF417HighLevelEncoderTestAdapter.java
core/src/test/java/com/google/zxing/pdf417/decoder/PDF417DecoderTestCase.java
core/src/test/java/com/google/zxing/pdf417/encoder/PDF417EncoderTestCase.java

By default multi-ECI encoding is disabled so that the encoding behavior is identical with the previous version. 
The implementation shares the classes that convert character input to a byte/ECI stream with the data-matrix encoder.
This PR also fixes an issue that the PDF417 decoder incorrectly decoded input with a leading ECI and no explicit latch to TEXT encoding.

Add support for multi-eci encoding for PDF417

---

core/src/main/java/com/google/zxing/common/MinimalECIInput.java
core/src/main/java/com/google/zxing/pdf417/decoder/DecodedBitStreamParser.java
core/src/main/java/com/google/zxing/pdf417/encoder/PDF417HighLevelEncoder.java
core/src/test/java/com/google/zxing/pdf417/decoder/PDF417DecoderTestCase.java

Also fixed issue that some multi-eci encoded PDF417 codes were missing ECIs
The unit test now also decodes the multi-eci encoding tests and verifies that the result is identical with the input.

Add multi-eci decoding for PDF417

---

core/src/main/java/com/google/zxing/common/ECIStringBuilder.java
core/src/main/java/com/google/zxing/datamatrix/decoder/DecodedBitStreamParser.java
core/src/main/java/com/google/zxing/pdf417/decoder/DecodedBitStreamParser.java

Besides the benefit of code reuse, the shared class is also more efficient in the no-ECI case so that the PDF417 decoder profits from that. With this PR we now have both a multi-eci encoder (..common.MinimalECIInput) and decoder (..common.ECIStringBuilder) that are shared between data-matrix and PDF417. I didn't look, but there may be other bar codes that don't yet support multi-eci, that could also make use of it.

Share the ECI string builder of the data matrix decoder with the PDF417 decoder

---

core/src/main/java/com/google/zxing/pdf417/encoder/PDF417HighLevelEncoder.java

… when neither a character-set nor multi-eci-encoding is selected.
This fixes issue #1163.

Replacing non ISO-8859-1 characters in PDF417 input with '?'

---

android/AndroidManifest.xml

While targetting to Android 12 SDK (API 31), there's a restriction to providing the flag `android:exported` to all the components (activity, service, receivers) having `<intent-filter>`. This PR sets this flag to all activities having intent filters which can be helpful for the client applications which are targeting to Android 12.
Closes: #1517

Specify `android:exported` to the activities having `<intent-filter>`

---

core/src/main/java/com/google/zxing/common/BitMatrix.java
core/src/main/java/com/google/zxing/pdf417/PDF417Reader.java
core/src/main/java/com/google/zxing/pdf417/detector/Detector.java
core/src/main/java/com/google/zxing/pdf417/detector/PDF417DetectorResult.java

Pull Request https://github.com/zxing/zxing/pull/1333 added support for scanning PDF417 barcodes at different orientations. We have a use case where we are using the orientation of the barcode to know the correct orientation of the page. With previous versions of zxing, we attempted to read barcodes from images with each orientation. With 3.5.0, the different orientations are now scanned in the Detector, with no way of the client to know which orientation the barcode was found in. This change stores the orientation in the result's metadata so that the orientation data can be used by clients of this library.
I also modified the rotation logic such that we don't clone the matrix when decoding with a rotation of 0.

Adds orientation of pdf417 barcode to Result metadata

---

README.md

Adds a description for the OkapiBarcode project to the README (it's currently missing).

Add description for OkapiBarcode project

---

README.md

nu-book/zxing-cpp is now reachable under zxing-cpp/zxing-cpp

update nu-book/zxing-cpp link

---

README.md

Please add my port of zxing for rust to the list of ports.

add rust port (rxing) to the list of ports

---

README.md

Please update the link for rxing (the rust port of zxing) as the repository has changed

update the link for rxing

---

core/src/main/java/com/google/zxing/qrcode/detector/FinderPatternFinder.java

cf. https://developer.android.com/reference/java/util/List#sort(java.util.Comparator%3C?%20super%20E%3E), "added in API level 24"

fix: 1358 - rolled back to old-fashioned Collections.sort for android 23

---

core/src/main/java/com/google/zxing/common/reedsolomon/GenericGF.java

I clarified that the size of the GF is assumed to be a power of two. Even though this might be obvious, it is important to clarify. Otherwise functions like
```java
/**
* Implements both addition and subtraction -- they are the same in GF(size).
*
* @return sum/difference of a and b
*/
static int addOrSubtract(int a, int b) {
return a ^ b;
}
```
make no sense at all. For this to hold, the field needs to have characteristic two. Clarifying that the size of the GF is assumed to be power of two, this criterium is met. In these cases `2` will also always be a primitive element, which makes the comment I changed more straightforward.
I also changed the integers to be displayed in binary, reflecting the interpretation of them as primitive polynomials much better. Arguably the comments …

Clarify that the size of the GF is a power of two

---

.gitignore

The IntelliJ IDEA project files are already ignored -- adding Eclipse IDE project files to the ignore list.

Ignore Eclipse IDE files

---

core/src/main/java/com/google/zxing/oned/Code128Writer.java

Space is a valid character in CodeSet B.

Allow space in Code128 CodeSet B

---

core/src/main/java/com/google/zxing/oned/Code128Writer.java
core/src/main/java/com/google/zxing/oned/OneDimensionalCodeWriter.java

This method is useful for encoding Code128 with a specific code set to a bool array. As no other class overrides this method, this change only affects Code128Writer.
I don't know that there's a strong argument against making this method public. With this method protected, it is necessary to first encode as a BitMatrix, extract the first row, and the convert the resulting BitArray to a bool array. This all can be avoided if the method is made public.

Make OneDimensionalCodeWriter.encode(content, hints) public

---

javase/src/test/java/com/google/zxing/client/j2se/MatrixToImageWriterTestCase.java

while [packaging for gentoo](https://bugs.gentoo.org/910497), it seems that not all platforms have support for tiff (openjdk-8 for example) which is used by the MatrixToImageWriter test in javase. this patch simply check that tested format is indeed part of the supported writers, [ignoring the test](https://github.com/junit-team/junit4/wiki/Assumptions-with-assume) if it isn't.

javase/test/matrix: check format support

---

core/src/main/java/com/google/zxing/oned/rss/expanded/decoders/FieldParser.java

This PR updates the GS1 AIs per the 2023 version of the GS1 spec, available here: https://www.gs1.org/standards/barcodes-epcrfid-id-keys/gs1-general-specifications
Where existing AI data lengths have been increased in the spec (a backwards-compatible change), the limits have simply been updated in the code.
Where existing AI data lengths have been decreased in the spec, or where AIs have been removed entirely from the spec (backwards-incompatible changes), the code has been left as-is (to not break existing use cases) and a comment has been added noting the discrepancy.

Update GS1 AIs according to 2023 specification

---

javase/src/main/java/com/google/zxing/client/j2se/DecodeWorker.java

Fixes https://github.com/zxing/zxing/issues/1682

Prevent --raw CLR option from failing if result.getRawBytes() is null

---

core/src/main/java/com/google/zxing/common/StringUtils.java
core/src/main/java/com/google/zxing/qrcode/decoder/DecodedBitStreamParser.java
core/src/main/java/com/google/zxing/qrcode/encoder/Encoder.java

Certain embedded JREs do not include lib/charsets.jar  This means that these platforms don't support Charsets outside of the six [standard Charsets](https://docs.oracle.com/javase/8/docs/api/java/nio/charset/Charset.html).  
#1330 made the assumption that the Shift JIS Charset *would* be available, so on platforms without Shift JIS support, attempting to load QRCodeWriter results in an UnsupportedCharsetException before attempting to encode any text.
This change, like the change in commit [a6273e3](https://github.com/zxing/zxing/commit/a6273e3bc788135e4ad755fe6a7c1a4bf74fcdc9), handles UnsupportedCharsetExceptions in the static initializers, then checks for the properly loaded SJIS Charset during encode and decode operations.
So as to not introduce any new test dependencies, the *tests* …

Support for platforms where SJIS is unavailable

---

javase/pom.xml

Also, switches to current artifact name `org.jcommander:jcommander`
https://jcommander.org/#_download
https://github.com/cbeust/jcommander/compare/1.82...1.83

Update jcommander 1.82 -> 1.83

---

core/src/main/java/com/google/zxing/qrcode/QRCodeWriter.java
core/src/test/java/com/google/zxing/qrcode/QRCodeWriterTestCase.java

This small commit makes public the "`renderResult`" method of the "`QRCodeWriter`" class.
The reason to promote this method as public is that I'm facing business case where, besides of generating the QR code as a PNG image, I also need to print information about the QR code itself (specifically, the QR version). Navigating through the code of zxing library, I noticed that the `com.google.zxing.qrcode.encoder.Encoder` allows me to have that (the QR metadata); however, by invoking that class I only have part of the equation (the `QRCode` DTO) ... I'm still needing to generate the `BitMatrix` in order to produce the QR image.
Here, I have two alternatives: either I invoke the `Encoder.encode` class by myself and repeat the same logic when invoking the `QRCodeWriter.encode` method; or I make …

Promote renderResult method to public

---

core/src/main/java/com/google/zxing/multi/qrcode/QRCodeMultiReader.java

The current use of `QRCodeMultiReader` has an issue with the loss of `SYMBOLOGY_IDENTIFIER`. This affects the ability to accurately determine if a QR code is GS1-compliant, as GS1-QR codes can be identified by the `SYMBOLOGY_IDENTIFIER` field being `]Q3` (refer to [GS1 Barcode Specifications](https://www.gs1.org/docs/barcodes/GS1_Barcodes_Fact_Sheet-GS1_2D_symbols.pdf)).
Added handling logic for `SYMBOLOGY_IDENTIFIER` in the `QRCodeMultiReader` class, incorporating it into the decoding result metadata.
- **Data Integrity**: Ensures the `SYMBOLOGY_IDENTIFIER` information is preserved, improving the completeness of decoding results.
- **Compatibility**: Enhances support for applications that require `SYMBOLOGY_IDENTIFIER` information, such as ]Q3 for GS1-QR.
- **Functional Consistency**: …

Fix SYMBOLOGY_IDENTIFIER Loss in QRCodeMultiReader to Ensure Data Integrity and Functional Consistency with QRCodeReader

---

README.md

This PR updates a ZXingObjC link in README, because its repository has been moved.

Update ZXingObjC link in README

---

core/src/main/java/com/google/zxing/pdf417/encoder/PDF417HighLevelEncoder.java
core/src/test/java/com/google/zxing/pdf417/encoder/PDF417EncoderTestCase.java

PDF417: Check that input is made of 0...127 chars when using Compaction.TEXT, throw an explicit exception if not the case

---

README.md
zxingorg/src/main/webapp/w/decode.jspx

As the app isn't on the Play Store any more (RIP!) I've removed the links from the readme and the website.

Remove broken links to Play Store

---

README.md

Adding Barcode-Lib4J to the third-party projects list. This Java library extends ZXing's 2D barcode functionality with vector/raster exports, professional printing features, and comprehensive GS1 validation.
The library maintains proper attribution to ZXing as documented in the credits section.

Add "Barcode-Lib4J" to the list of third-party projects
